### Read all films 
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all films filtered by duration minimum
GET {{baseUrl}}/films/?minimum-duration=value

### Find film by id
GET {{baseUrl}}/films/1 

### Create a film

POST {{baseUrl}}/films
Content-Type: application/json
    
    {
        "title": "The Godfather",
        "director": "Francis Ford Coppola",
        "duration": 175
    }